#!/usr/bin/env bash

prefix="hkvb_elastic_metricbeat_node__$1"
prefix="hkvb_elastic_metricbeat_node__$1"

executionplane --silent docker container prune --force

if [[ "hkvb_elastic_metricbeat_node__metrics_node_metricbeat_config" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "hkvb_elastic_metricbeat_node__metrics_node_metricbeat_config"
		result=$(docker volume ls | grep "hkvb_elastic_metricbeat_node__metrics_node_metricbeat_config")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "hkvb_elastic_metricbeat_node__metrics_node_metricbeat_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "hkvb_elastic_metricbeat_node__metrics_node_metricbeat_volume"
		result=$(docker volume ls | grep "hkvb_elastic_metricbeat_node__metrics_node_metricbeat_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
