#!/usr/bin/env bash

prefix="vcw_module_hkvb_elastic_heartbeat__$1"
prefix="vcw_module_hkvb_elastic_heartbeat__$1"

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_config" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_heartbeat__heartbeat_config
fi

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_entrypoint" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_heartbeat__heartbeat_entrypoint
fi

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_heartbeat__heartbeat_data_volume
fi

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_monitors_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_elastic_heartbeat__heartbeat_monitors_volume
fi

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_config" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_elastic_heartbeat__heartbeat_config:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/elastic/heartbeat/_module/volumes/heartbeat_config/* /vcw/pwd
fi

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_entrypoint" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_elastic_heartbeat__heartbeat_entrypoint:/vcw/bin ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/elastic/heartbeat/_module/volumes/heartbeat_entrypoint/* /vcw/bin
fi

if [[ "vcw_module_hkvb_elastic_heartbeat__heartbeat_monitors_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_elastic_heartbeat__heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/elastic/heartbeat/_module/volumes/heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
fi
