---
version: '3'
services:

# START SERVICE hkvb/elastic/apm/traefik
  apm:
    image: ${VCW_REGISTRY}docker.elastic.co/apm/apm-server:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200']
    command: []
    volumes: []
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${APM_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${APM_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'

      labels: [traefik.enable=true,traefik.docker.network=${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay,
      "traefik.http.middlewares.${VCW_STACK_GLOBAL_STACKPREFIX}_apm.stripprefix.prefixes=/${VCW_STACK_GLOBAL_URLPREFIX}/apm,/${VCW_STACK_GLOBAL_URLPREFIX}/apm/",
      traefik.http.services.${VCW_STACK_GLOBAL_STACKPREFIX}_apm.loadbalancer.server.port=8200,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_apm.middlewares=${VCW_STACK_GLOBAL_STACKPREFIX}_apm@docker,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_apm.entrypoints=conteco,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_apm.rule=PathPrefix("/${VCW_STACK_GLOBAL_URLPREFIX}/apm") ]
${APM_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/elastic/apm/traefik

networks: {${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay: { external: true }, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
