#!/usr/bin/env bash

prefix="hkvb_elastic_search_rest__$1"
prefix="hkvb_elastic_search_rest__$1"

if [[ "hkvb_elastic_search_rest__api_rest_elasticsearch_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_elastic_search_rest__api_rest_elasticsearch_data_volume
fi

if [[ "hkvb_elastic_search_rest__api_rest_elasticsearch_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v hkvb_elastic_search_rest__api_rest_elasticsearch_data_volume:/conteco/pwd ${VCW_REGISTRY}hkvb/controlplane.vcw console cmd tar -C / -xvf /source/hkvb/elastic/search/rest/_module/volumes/api_rest_elasticsearch_data_volume.tar
fi
