---
version: '3'
services:

# START SERVICE hkvb/elastic/journalbeat
  journalbeat:
    image: ${VCW_REGISTRY}docker.elastic.co/beats/journalbeat:7.11.2
    environment: ['ES_JOURNALBEAT_LOGGING_LEVEL=${VCW_STACK_JOURNALBEAT_ENVIRONMENT_LOGGING_LEVEL}']
    command: [/vcw/bin/docker-entrypoint]
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_config:/vcw/pwd','${VCW_STACK_GLOBAL_STACKPREFIX}_entrypoint:/vcw/bin','${VCW_STACK_GLOBAL_STACKPREFIX}_volume:/usr/share/journalbeat/data','/etc:/hostfs/etc:ro','${VCW_STACK_JOURNALBEAT_VOLUMES_HOST_JOURNALPATH}:/hostfs/var/log/journal:ro']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${VCW_STACK_JOURNALBEAT_DEPLOY_MODE}
      resources:
        limits:
          memory: '${VCW_STACK_JOURNALBEAT_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_JOURNALBEAT_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
    user: root
${VCW_STACK_JOURNALBEAT_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/elastic/journalbeat

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_config: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_entrypoint: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
