---
version: '3'
services:

# START SERVICE hkvb/elastic/filebeat
  filebeat:
    image: ${VCW_REGISTRY}docker.elastic.co/beats/filebeat:7.11.2
    environment: ['ES_FILEBEAT_FILEPATHS=${FILEBEAT_ENVIRONMENT_FILEPATHS}','ES_FILEBEAT_LOGGING_LEVEL=${FILEBEAT_ENVIRONMENT_LOGGING_LEVEL}']
    command: [/vcw/bin/docker-entrypoint]
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_config:/vcw/pwd','${VCW_STACK_GLOBAL_STACKPREFIX}_entrypoint:/vcw/bin','${VCW_STACK_GLOBAL_STACKPREFIX}_volume:/usr/share/filebeat/data','${VCW_STACK_GLOBAL_STACKPREFIX}_ingest_volume:/vcw/ingest','/etc:/hostfs/etc:ro'${FILEBEAT_ENVIRONMENT_FILEPATHS_MAPPING}]
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${FILEBEAT_DEPLOY_MODE}
      resources:
        limits:
          memory: '${FILEBEAT_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${FILEBEAT_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${FILEBEAT_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/elastic/filebeat

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_config: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_entrypoint: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_volume: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_ingest_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
