#!/usr/bin/env bash

prefix="hkvb_elastic_metricbeat__$1"
prefix="hkvb_elastic_metricbeat__$1"

if [[ "hkvb_elastic_metricbeat__metrics_metricbeat_config" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_elastic_metricbeat__metrics_metricbeat_config
fi

if [[ "hkvb_elastic_metricbeat__metrics_metricbeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_elastic_metricbeat__metrics_metricbeat_volume
fi

if [[ "hkvb_elastic_metricbeat__metrics_metricbeat_config" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v hkvb_elastic_metricbeat__metrics_metricbeat_config:/vcw/pwd ${VCW_REGISTRY}hkvb/controlplane.vcw console cmd cp -r /source/hkvb/elastic/metricbeat/_module/volumes/metrics_metricbeat_config/* /vcw/pwd
fi
