---
version: '3'
services:

# START SERVICE hkvb/elastic/metricbeat
  metricbeat:
    image: ${VCW_REGISTRY}hkvb/elastic.metricbeat:7.11.2
    environment: ['ES_METRICBEAT_LOGGING_LEVEL=${VCW_STACK_METRICBEAT_MODULE_METRICBEAT_LOGGING_LEVEL}']
    command: []
    volumes: ['/etc:/hostfs/etc:ro','${VCW_STACK_GLOBAL_STACKPREFIX}_config:/vcw/pwd','${VCW_STACK_GLOBAL_STACKPREFIX}_volume:/usr/share/metricbeat/data']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${VCW_STACK_METRICBEAT_DEPLOY_MODE}
      resources:
        limits:
          memory: '${VCW_STACK_METRICBEAT_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_METRICBEAT_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_METRICBEAT_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/elastic/metricbeat

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_config: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
